services:
  - type: web
    name: blitzapp
    env: node
    plan: starter
    buildCommand: npm ci --production && blitz build
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true
